### ISSUE TITLE
课程 192 出现的错误

### ISSUE THREAD

**Issue by wongdean** [kadaliao/knowledge-exporter#4]
1. 
```python
Traceback (most recent call last):
  File "/Users/coco/anaconda3/envs/pytorch/bin/knowledge-exporter", line 8, in <module>
    sys.exit(main())
  File "/Users/coco/anaconda3/envs/pytorch/lib/python3.6/site-packages/knowledge_exporter/__init__.py", line 7, in main
    app.run()
  File "/Users/coco/anaconda3/envs/pytorch/lib/python3.6/site-packages/knowledge_exporter/exporter.py", line 64, in run
    asyncio.get_event_loop().run_until_complete(self.coro(args.column_id))
  File "/Users/coco/anaconda3/envs/pytorch/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/Users/coco/anaconda3/envs/pytorch/lib/python3.6/site-packages/knowledge_exporter/exporter.py", line 51, in coro
    title = await task
  File "/Users/coco/anaconda3/envs/pytorch/lib/python3.6/asyncio/tasks.py", line 458, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/Users/coco/anaconda3/envs/pytorch/lib/python3.6/site-packages/knowledge_exporter/geektime.py", line 44, in download_article
    await self._process_and_print(filename)
  File "/Users/coco/anaconda3/envs/pytorch/lib/python3.6/site-packages/knowledge_exporter/geektime.py", line 77, in _process_and_print
    {"path": f"./{filename}.pdf"}, margin={"top": 32, "bottom": 32}
  File "/Users/coco/anaconda3/envs/pytorch/lib/python3.6/site-packages/pyppeteer/page.py", line 1462, in pdf
    with open(options['path'], 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './SQL必知必会/801_第二章：SQL性能优化篇_118101_28丨从磁盘I/O的角度理解SQL查询的成本.pdf'

```
这个地方必定会出现错误，建议是否做一个“缓存”，将未成功的保存，待所有的下载完成后重试？

2. 未能有效检测是否登录成功
有时会遇到登录不成功的情况，这样下载的文件都是未登录版本的。未发现复现条件，在尝试了3次下载中共出现1次。

**Comment by kadaliao** [comment]
@wongdean 问题1已经修复。可以`pip install --upgrade knowledge-exporter`更新试试。

Relative: #1

**Comment by wongdean** [comment]
已经修复，多谢，另外我试验的合并多个pdf并未生效，而且下载的文章命名有点长了。。

**Comment by kadaliao** [comment]
选项里的几个功能这几天会加上。

文件名故意保存成这样的，主要是保持有序，作为中间文件最后合并成一个PDF。

wongdean <notifications@github.com>于2020年9月28日 周一下午10:07写道：

**Comment by kadaliao** [comment]
@wongdean 登录问题也解决了，可以`pip install knowledge-exporter==1.1.1`试试
